USE CUSTOMER_DB;

DROP TABLE IF EXISTS OUTPUTQ4;

CREATE TABLE OUTPUTQ4(C_NAME VARCHAR(40), CITY VARCHAR(35), COUNTRY VARCHAR(20), CUST_GRADE DECIMAL(10, 0));

DELIMITER $$

DROP PROCEDURE IF EXISTS DETAILS;

CREATE PROCEDURE DETAILS()
BEGIN
	DECLARE DONE INT DEFAULT FALSE;
	DECLARE C_NAME VARCHAR(40);
	DECLARE CITY VARCHAR(35);
	DECLARE COUNTRY VARCHAR(20);
	DECLARE CUST_GRADE DECIMAL(10, 0);
	DECLARE DETAILS_CURSOR CURSOR FOR SELECT CUST_NAME, CUST_CITY, CUST_COUNTRY, GRADE FROM CUSTOMER WHERE (AGENT_CODE LIKE "A00%");
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;

	OPEN DETAILS_CURSOR;

	LABEL: LOOP
	FETCH DETAILS_CURSOR INTO C_NAME, CITY, COUNTRY, CUST_GRADE;
            IF DONE THEN LEAVE LABEL;
			END IF;
			INSERT INTO OUTPUTQ4 VALUES(C_NAME, CITY, COUNTRY, CUST_GRADE);
	END LOOP;
	CLOSE DETAILS_CURSOR;
    SELECT * FROM OUTPUTQ4;
END $$

CALL DETAILS();